[build]
    command = "npm run build"
    publish = "dist"
    functions = "functions/"

[[redirects]]
    from = "/api/update-order-status"
    to = "/.netlify/functions/update-order-status"
    status = 200